//
//  FOODitStyleKit.h
//  FOODit
//
//  Created by Marc Humet on 15/12/14.
//  Copyright (c) 2014 EQUUS LIFE SL. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface FOODitStyleKit : NSObject

// Colors
+ (UIColor*)characoal;
+ (UIColor*)chicken;
+ (UIColor*)seafood;

// Drawing Methods
+ (void)drawExpandbutton;
+ (void)drawMealcard__curve;
+ (void)drawTagcharcoal;
+ (void)drawTagcheese;
+ (void)drawTagchicken;
+ (void)drawTaggrilled;
+ (void)drawTaghighprotein;
+ (void)drawTaglamb;
+ (void)drawTagpasta;
+ (void)drawTagpeanut;
+ (void)drawTagpork;
+ (void)drawTagsnack;
+ (void)drawTagspicy;
+ (void)drawTagstarter;
+ (void)drawTagsweet;
+ (void)drawTagvegetarian;
+ (void)drawGenerictag;
+ (void)drawTagseafood;
+ (void)drawMealcard__curve2WithFraction: (CGFloat)fraction;

@end
